# Generated by Django 5.2.1 on 2025-05-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0007_alter_cartitem_options_cartitem_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nft",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="nft_images/"),
        ),
    ]
